/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef case_CONSTANTS_H
#define case_CONSTANTS_H

#include "case_types.h"



class caseConstants {
 public:
  caseConstants();

};

extern const caseConstants g_case_constants;



#endif
